# Generated by Django 5.2.7 on 2025-11-29 13:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_building_alert'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='read_by',
            field=models.ManyToManyField(blank=True, related_name='read_alerts', to=settings.AUTH_USER_MODEL),
        ),
    ]
