# Generated by Django 5.2.7 on 2025-12-07 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_alert_read_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_picture_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
