# Generated by Django 5.2.7 on 2025-12-07 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_profile_profile_picture_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='school_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
