# Generated by Django 5.2.7 on 2025-12-07 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_profile_school_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
