# Generated by Django 5.2.7 on 2025-12-07 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0006_profile_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('emergency', 'Emergency'), ('safety', 'Safety Concern'), ('location_share', 'Location Share'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
